### ISSUE TITLE
S3 As a player, I want the system to assign me a game role randomly at the start of the  game so that the game is fair and maintains the element of surprise.

### ISSUE THREAD

**Issue by DaKnechtCoder** [sopra-fs24-group-42/client#16]
**Development Tasks**
Frontend:
- [ ] sopra-fs24-group-42/client#12
- [ ] sopra-fs24-group-42/client#13
- [ ] sopra-fs24-group-42/client#14
- [ ] sopra-fs24-group-42/client#15

Backend: 
- [ ] sopra-fs24-group-42/server#46
- [ ] sopra-fs24-group-42/server#47
- [ ] sopra-fs24-group-42/server#48
- [ ] sopra-fs24-group-42/server#49

**Acceptance Criteria:**
- [ ] Upon game start, the system randomly assigns roles to all players in the room.
- [ ] Players receive a notification of their role without revealing it to other players. 
- [ ] The role assignment is logged in to the database.
